apiVersion: v1
kind: Secret
metadata:
  name: sftp-secrets
  annotations:
    note: "placeholder values are base64-encoded"
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0=
  SFTP_HOST_KEY: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
